---
title: "Group Project 4 COVID"
author: 'covid_p11'
date: '2022-03-28'
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggplot2)
library(maps)
library(plotly)
library(caret)
library(dplyr)
```

Topic: COVID-19 New cases and finicial market
visualisation dashboard: Shiny app
```{r}
covid = read.csv("D:/data/owid-covid-data.csv")
glimpse(covid)
```
data clean
```{r}
covid2 = covid %>% drop_na(new_cases, new_cases_smoothed, total_deaths, new_deaths, new_deaths_smoothed, total_cases_per_million, new_cases_per_million, new_cases_smoothed_per_million, total_deaths_per_million, new_deaths_per_million, new_deaths_smoothed_per_million, new_vaccinations, new_vaccinations_smoothed, new_vaccinations_smoothed_per_million, population, population_density, median_age,extreme_poverty, new_tests)
glimpse(covid2)
unique(covid2$location)
```

# Impact on finicial market

# relationship between new cases and vaccination

# Initial analysis for new_cases_smoothed
```{r}
covid1 <- covid2
covid1$month <- strftime(covid1$date, "%m")
covid1$year  <- strftime(covid1$date, "%Y")

covid1_aggregate <- aggregate(new_cases_smoothed~month+year, 
                  covid1,
                  FUN = sum)
```

```{r}
covid1_aggregate$concatenated <- paste(covid1_aggregate$month, covid1_aggregate$year)

covid3 <- covid1_aggregate %>% mutate(month_year = as.Date(covid1_aggregate$concatenated,  format="%m-%y"))

```

```{r}
ggplot(covid1_aggregate, aes(x= new_cases_smoothed, y= concatenated)) +
  geom_bar(stat = 'identity')
```

