---
title: "Data3888 project report"
author: "Covid_p11"
date: '2022-05-25'
output:
  html_document:
    fig_caption: yes
    number_sections: yes
    self_contained: yes
    theme: flatly
    toc: yes
    toc_depth: 3
    toc_float: yes
    code_folding: hide
  pdf_document:
    toc: yes
    toc_depth: '3'
---

# Executive Summary

## Short Description

## Main findings

## Relevance of analysis


# Backgrounds

The global spread of SARS-COV2 (Covid-19) in the beginning of 2020 resulted in millions of deaths and ICU hospitalisations worldwide. The economy was severely impacted by this pandemic and as a result, public equity markets of leading countries (Australia, Japan, India, USA and China) Most equity markets reached a peak in February 2019, and dipped around March 23 as a majority of the world’s largest economy were forced into lockdown. (Seven & Yilmaz 2021) This report evaluates the impact of Covid-19 on global equity markets and provides a guide for retail traders and investors. Using data collected from (WHERE DID WE GET OUR DATA AGAIN?) we conducted basic linear regressions and correlation matrices as analysis for the modeling on a user Shiny app to better communicate the effects of Covid-19 on relevant public equity markets. We used various modeling algorithms (KNN, KSV, Cv, Clustering)as an attempt to predict the accuracies in trends between interested variables relating to Covid and the prices of equity markets to highlight any relevant relationships between the two data. 

A hypothesis formulated by (Diermier, Ibbotson, & Siegel, 1984; Ibbotson & Chen, 2003) states that a stock market’s success is reliant on the success of businesses. With lockdown and strict social distancing laws in place globally, business and trade were impacted and called to a halt. These series of events layed path for negative returns, greater volatility, and higher trading volume in the global equity market (Harjoto 2021) As there are no current studies to report on the effect of stock markets and daily cases and mortality rates, through this report we aim to make preliminary findings and identify variables which are responsible for changes in equity markets and relate them to the current Covid-19 crisis to identify how this virus has caused instability in stocks. With the introduction of the Covid-19 pandemic, it is hypothesized that global equity markets will have a correlation to the status of cases, tests and vaccinations.


# Approach & Method



# Results




# Discussion



# Conclusion

Our group combines omics and Stock Quotes data to analyze the effects of Covid-19 on relevant public equity markets. We have found the prices of equity markets are closely related to this global pandemic by collecting the information from leading countries (Australia, Japan, India, USA and China) and analyzed it via the linear regressions and correlation matrices. We obtained the daily stock prices for 15 kinds of stocks from USA stock market, which is universally-acknowledged as a typical one, through a financial database from yahoo, and then using machine learning models (KNN, RDA, RPART) to make a predication. We also developed a shiny app as a guide for retail traders and investors. As a result, the users can have a clear understanding of the impact of Covid-19 on the stock market, based on which they can make wiser investment decisions.


# Group Contribution


# References

- Harjoto, M., Rossi, F., Lee, R., & Sergi, B. (2021). How do equity markets react to COVID-19? Evidence from emerging and developed countries. Journal Of Economics And Business, 115, 105966. https://doi.org/10.1016/j.jeconbus.2020.105966

- Seven, Ü., & Yılmaz, F. (2021). World equity markets and COVID-19: Immediate response and recovery prospects. Research In International Business And Finance, 56, 101349. https://doi.org/10.1016/j.ribaf.2020.101349
